### ISSUE TITLE
Service worker errors preventing trip display

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#1005]
Planned trips fail to render in some browsers with a cached version of the site.

Seems to be dependent on having an older version of the service worker previously installed. On Chrome, the planned trips fail to render; on Firefox, they show, but there are console errors.

See [this similar issue with Chrome 64](https://stackoverflow.com/questions/48463483/what-causes-a-failed-to-execute-fetch-on-serviceworkerglobalscope-only-if).

Chrome errors:
`Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode`

<Details>
Failed to load resource: net::ERR_FAILED
main.js:1 failed to plan trip
(anonymous) @ main.js:1
main.js:1 Object
(anonymous) @ main.js:1
jquery-3.2.1.min.js:2 jQuery.Deferred exception: Cannot read property 'indexOf' of undefined TypeError: Cannot read property 'indexOf' of undefined
    at c.setItinerariesError (https://gophillygo.org/static/scripts/main.js:1:60186)
    at https://gophillygo.org/static/scripts/main.js:1:49295
    at j (https://code.jquery.com/jquery-3.2.1.min.js:2:29999)
    at k (https://code.jquery.com/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
service-worker.js:42 TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at service-worker.js:29
    at <anonymous>
(anonymous) @ service-worker.js:42
Promise.catch (async)
(anonymous) @ service-worker.js:41
Promise.then (async)
(anonymous) @ service-worker.js:23
service-worker.js:43 FetchEvent {isTrusted: true, request: Request, clientId: "88f03957-8695-49a7-9b76-3a6097187387", isReload: false, preloadResponse: Promise, …}
(anonymous) @ service-worker.js:43
Promise.catch (async)
(anonymous) @ service-worker.js:41
Promise.then (async)
(anonymous) @ service-worker.js:23
The FetchEvent for "https://gophillygo.org/?origin=39.9757287%2C-75.1351794&originText=1711%20N%20Howard%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019122&mode=TRANSIT%2CWALK&maxWalk=482802&wheelchair=false&bikeTriangle=any&arriveBy=false&dateTime=&destination=39.9517931%2C-75.2498138&destinationText=Fox%20and%20Maple%20Day" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ service-worker.js:23
service-worker.js:44 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at service-worker.js:44
    at <anonymous>
</Details>

On Firefox:
![image](https://user-images.githubusercontent.com/960264/37120673-0b701d1e-2229-11e8-8167-d3b0ba7c3787.png)

**Comment by flibbertigibbet** [comment]
Duplicate of #1010
