### ISSUE TITLE
JS tests failing

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#1084]
`npm run gulp-test` fails locally with a karma/gulp error:

```
10 09 2018 16:41:24.734:ERROR [plugin]: Error during loading "/opt/app/src/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
10 09 2018 16:41:24.810:ERROR [plugin]: Error during loading "/opt/app/src/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
10 09 2018 16:41:24.874:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
10 09 2018 16:41:24.874:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 09 2018 16:41:24.875:ERROR [karma]: Found 1 load error
10 09 2018 16:41:25.181:WARN [karma]: Port 9876 in use
10 09 2018 16:41:25.182:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9877/
10 09 2018 16:41:25.182:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 09 2018 16:41:25.183:ERROR [karma]: Found 1 load error
[16:41:25] Finished 'test:production' after 7.22 s
[16:41:25] 'test:production' errored after 7.22 s
[16:41:25] Error: task completion callback called too many times
    at finish (/opt/app/src/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/opt/app/src/node_modules/orchestrator/lib/runTask.js:29:3)
    at /opt/app/src/gulpfile.js:284:17
    at removeAllListeners (/opt/app/src/node_modules/karma/lib/server.js:380:7)
    at /opt/app/src/node_modules/karma/lib/server.js:391:9
    at Server.close (net.js:1620:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1671:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by flibbertigibbet** [comment]
Probably a transient npm package issue; fixed after running `npm cache clean --force` and reinstalling.
