### ISSUE TITLE
Occasional npm run gulp-watch errors

### ISSUE THREAD

**Issue by CloudNiner** [azavea/cac-tripplanner#578]
The process occasionally crashes with the error:
```
[19:19:19] Starting 'common:build'...
[19:19:19] 'common:build' errored after 43 μs
[19:19:19] Error: The thunkFunction already filled
    at child (/opt/app/src/node_modules/gulp-sequence/node_modules/thunks/thunks.js:158:32)
    at Gulp.thunkFunction (/opt/app/src/node_modules/gulp-sequence/node_modules/thunks/thunks.js:153:14)
    at module.exports (/opt/app/src/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/opt/app/src/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/opt/app/src/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/opt/app/src/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/opt/app/src/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/opt/app/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
    at emitTwo (events.js:87:13)
    at Gaze.emit (events.js:172:7)
    at Gaze.emit (/opt/app/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
```

Possibly related? https://github.com/teambition/gulp-sequence/issues/2

Workaround is to restart the process or manually run `npm run gulp-development` whenever static asset changes are made.

**Comment by anjunatl** [comment]
@CloudNiner I think https://github.com/teambition/gulp-sequence/issues/2 may be related as you mentioned. I had the same error appear occasionally when a `watch` task would run a sequenced set of tasks.

I modified my usage of `gulp-sequence` to use the callback pattern as mentioned by @zensh here: https://github.com/teambition/gulp-sequence/issues/2#issuecomment-78720934 - As far as I can tell, it's resolved my problem.
